### ISSUE TITLE
[desktop_webview_window][linux] Does not compile

### ISSUE THREAD

**Issue by marcinczepielahumanit** [MixinNetwork/flutter-plugins#159]
Hi, I have a problem with compiling an app after adding desktop_webview_window: ^0.1.6.

Command 
`sudo apt install webkit2gtk-4.0`
Does not work, it returns 
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package webkit2gtk-4.0
E: Couldn't find any package by glob 'webkit2gtk-4.0'
`

After running command

I can see on the list of packeges
`libwebkit2gtk-4.0-37/focal-updates,focal-security,now 2.36.8-0ubuntu0.20.04.1 amd64 [installed]
libwebkit2gtk-4.0-dev/focal-updates,focal-security,now 2.36.8-0ubuntu0.20.04.1 amd64 [installed]
`

###Compiling error:
`
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error -luuid -lpthread -ldl CMakeFiles/box_machine_desktop.dir/main.cc.o CMakeFiles/box_machine_desktop.dir/my_application.cc.o
CMakeFiles/box_machine_desktop.dir/flutter/generated_plugin_registrant.cc.o  -o intermediates_do_not_run/box_machine_desktop
-Wl,-rpath,/home/linux/Documents/Box-Machine-Desktop/build/linux/x64/debug/plugins/desktop_webview_window:/home/linux/Documents/Box-Machine-Desktop/build/linux/x64/debug/plugins/desktop_window:/home/linux/Documents/Box-Machine-Desktop/linux/flutter/ephemeral:
plugins/desktop_webview_window/libdesktop_webview_window_plugin.so  plugins/desktop_window/libdesktop_window_plugin.so  /home/linux/Documents/Box-Machine-Desktop/linux/flutter/ephemeral/libflutter_linux_gtk.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5support.so.0: undefined reference to `dlopen@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5.so.3: undefined reference to `ns_name_uncompress@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5support.so.0: undefined reference to `dlerror@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: undefined reference to `lstat@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5support.so.0: undefined reference to `dlclose@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5.so.3: undefined reference to `fstat@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: undefined reference to `stat@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5support.so.0: undefined reference to `dlsym@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libkrb5.so.3: undefined reference to `res_nsearch@GLIBC_2.34'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +1 ms] ninja: build stopped: subcommand failed.
[  +12 ms] Building Linux application... (completed in 4.4s)
[        ] Exception: Build process failed
[   +1 ms] "flutter run" took 4,907ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

`

**Comment by boyan01** [comment]
You can try this. (use **apt-get** instead of **apt**)

```
sudo apt-get install webkit2gtk-4.0
```

I'll update it to right apt package name lately.
