### ISSUE TITLE
[pasteboard][Windows] Copy image to clipboard is not working

### ISSUE THREAD

**Issue by annd22** [MixinNetwork/flutter-plugins#188]
Hi, 

I currently copy the image to clipboard with `Pasteboard.writeFiles([...])`

In the app, I successfully get the image from clipboard with `Pasteboard.image`

But when I go to another chat app (Facebook Messenger,...), I cannot paste the image by `control + V`.

Please help me check this, Thanks!

**Comment by damywise** [comment]
I have the same issue, has anyone found the fix to this?
Logs: 
```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method image on channel pasteboard)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      PasteboardPlatformIO.image (package:pasteboard/src/pasteboard_platform_io.dart:32:19)
<asynchronous suspension>
```
