### ISSUE TITLE
"Zone mismatch" message

### ISSUE THREAD

**Issue by 459217974** [MixinNetwork/flutter-plugins#249]
Starting with Flutter 3.10, the framework detects mismatches when using Zones and reports them to the console in debug builds.
The runWebViewTitleBarWidget method in desktop_webview_window does not meet this rule.

```
======== Exception caught by Flutter framework =====================================================
The following assertion was thrown during runApp:
Zone mismatch.

The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
When the exception was thrown, this was the stack: 
#0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:497:29)
#1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:502:6)
#2      runApp (package:flutter/src/widgets/binding.dart:1080:18)
#3      runWebViewTitleBarWidget.<anonymous closure> (package:desktop_webview_window/src/title_bar.dart:34:7)
#8      runWebViewTitleBarWidget (package:desktop_webview_window/src/title_bar.dart:31:3)
#9      main (package:*********/main.dart:149:7)
#10     _runMain.<anonymous closure> (dart:ui/hooks.dart:129:23)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 4 frames from dart:async)
====================================================================================================
```

## Reproduce Steps

```dart
void main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
  if (runWebViewTitleBarWidget(args)) {  // Causing a warning
    return;
  }
}
```

## Expected behavior

```dart
bool runWebViewTitleBarWidget(
  List<String> args, {
  WidgetBuilder? builder,
  Color? backgroundColor,
  void Function(Object error, StackTrace stack)? onError,
}) {
  if (args.isEmpty || args[0] != 'web_view_title_bar') {
    return false;
  }
  final webViewId = int.tryParse(args[1]);
  if (webViewId == null) {
    return false;
  }
  final titleBarTopPadding = int.tryParse(args.length > 2 ? args[2] : '0') ?? 0;
  runZonedGuarded(
    () {
      WidgetsFlutterBinding.ensureInitialized();  // add this line
      runApp(_TitleBarApp(
        webViewId: webViewId,
        titleBarTopPadding: titleBarTopPadding,
        backgroundColor: backgroundColor,
        builder: builder ?? _defaultTitleBar,
      ));
    },
    onError ??
        (e, s) {
          debugPrint('WebViewTitleBar: unhandled expections: $e, $s');
        },
  );

  return true;
}
```

**Version (please complete the following information):**
 - Flutter Version: v3.10.1
 - OS: all platform
 - plugin: desktop_webview_window:0.2.0

**Comment by 459217974** [comment]
https://docs.flutter.dev/release/breaking-changes/zone-errors

**Comment by 459217974** [comment]
#250
