### ISSUE TITLE
Getting error in Windows (desktop_multi_window)

### ISSUE THREAD

**Issue by utpalruparel** [MixinNetwork/flutter-plugins#377]
Hello,

I am using 
  desktop_multi_window:  0.2.0
 desktop_lifecycle:  0.1.1
I am getting error like below in Windows when I implemented in my project. When I run separately its working fine.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method broadcast on channel mixin.one/flutter_multi_window_channel)
[        ] #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)

Can anyone explain? Tried everything.

**Comment by felixkriechbaum** [comment]
I experience similar issues but on macos.
Before anyone asks, yes i completely restarted the app
When I create new Window my app crashes with:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel macos_window_utils/window_manipulator)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      WindowManipulator.initialize (package:macos_window_utils/window_manipulator.dart:43:5)
window_manipulator.dart:43
<asynchronous suspension>
#2      Window.initialize (package:flutter_acrylic/window.dart:56:7)
window.dart:56
<asynchronous suspension>
#3      main (package:xpaste/main.dart:20:5)
main.dart:20
<asynchronous suspension>`
