### ISSUE TITLE
[desktop_webview_window] Does not work on windows 10

### ISSUE THREAD

**Issue by neylsongularte** [MixinNetwork/flutter-plugins#63]
```
Flutter is already up to date on channel stable
Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (8 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2
```

Exception

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(0, failed to show window, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177)
<asynchronous suspension>
#2      WebviewWindow.create (package:desktop_webview_window/desktop_webview_window.dart:67)
<asynchronous suspension>
#3      BotoesDeOpcoesDesktop.build.<anonymous closure> (package:app/app.dart:52)
<asynchronous suspension>
```

**Comment by neylsongularte** [comment]
I move this on top the main.dart and work.

```
if (runWebViewTitleBarWidget(args)) {
    return;
  }
```

thanks
